// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4YlgSoADZB18CPAKh6DKj3quQW9CoIa8',
    appId: '1:790419883700:web:4c97af722a4c7803c039e1',
    messagingSenderId: '790419883700',
    projectId: 'elecko26-536e0',
    authDomain: 'elecko26-536e0.firebaseapp.com',
    databaseURL: 'https://elecko26-536e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elecko26-536e0.firebasestorage.app',
    measurementId: 'G-GVTF7NCQQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAujsJ_FiR2lDEBE4anf_P_13CAZnLsJKw',
    appId: '1:790419883700:android:a74d49f37c68ea6fc039e1',
    messagingSenderId: '790419883700',
    projectId: 'elecko26-536e0',
    databaseURL: 'https://elecko26-536e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elecko26-536e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHYzjyLYT4RPN6XmMe1dBHIY5cBKWsNxQ',
    appId: '1:790419883700:ios:de3c8e5a2d00dd32c039e1',
    messagingSenderId: '790419883700',
    projectId: 'elecko26-536e0',
    databaseURL: 'https://elecko26-536e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elecko26-536e0.firebasestorage.app',
    androidClientId: '790419883700-h41in708p3h0pa7j41o4nd4mf8o46on7.apps.googleusercontent.com',
    iosClientId: '790419883700-s6idu8ub76bsm76jrcqbe2k4ai3fv73g.apps.googleusercontent.com',
    iosBundleId: 'com.elecko26.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHYzjyLYT4RPN6XmMe1dBHIY5cBKWsNxQ',
    appId: '1:790419883700:ios:9cad0944b8e6542ec039e1',
    messagingSenderId: '790419883700',
    projectId: 'elecko26-536e0',
    databaseURL: 'https://elecko26-536e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elecko26-536e0.firebasestorage.app',
    androidClientId: '790419883700-h41in708p3h0pa7j41o4nd4mf8o46on7.apps.googleusercontent.com',
    iosClientId: '790419883700-03rnjkt5h69eomc77p9cketr23lhi3g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4YlgSoADZB18CPAKh6DKj3quQW9CoIa8',
    appId: '1:790419883700:web:4fa1afa0ffce9ed4c039e1',
    messagingSenderId: '790419883700',
    projectId: 'elecko26-536e0',
    authDomain: 'elecko26-536e0.firebaseapp.com',
    databaseURL: 'https://elecko26-536e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elecko26-536e0.firebasestorage.app',
    measurementId: 'G-45N8FZKZR2',
  );

}