// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5nifY1s4HyYcTf3Kw63pDdFlN0mJ-FPA',
    appId: '1:813263083099:web:ea9d0ea13b75bd8b1e517e',
    messagingSenderId: '813263083099',
    projectId: 'elecko26-585b0',
    authDomain: 'elecko26-585b0.firebaseapp.com',
    storageBucket: 'elecko26-585b0.firebasestorage.app',
    measurementId: 'G-45MVYT5CK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLbgDdhErvac9BLuwXbI-F7xla8Lfc0Ww',
    appId: '1:813263083099:android:4d90071dd46eb31e1e517e',
    messagingSenderId: '813263083099',
    projectId: 'elecko26-585b0',
    storageBucket: 'elecko26-585b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKkkVYZ_BqO7CudU80A3v1KjOx6aT6NRQ',
    appId: '1:813263083099:ios:50af136a181f5c1f1e517e',
    messagingSenderId: '813263083099',
    projectId: 'elecko26-585b0',
    storageBucket: 'elecko26-585b0.firebasestorage.app',
    iosBundleId: 'com.jtsgrit0.elecko26',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKkkVYZ_BqO7CudU80A3v1KjOx6aT6NRQ',
    appId: '1:813263083099:ios:200f1107ab55fced1e517e',
    messagingSenderId: '813263083099',
    projectId: 'elecko26-585b0',
    storageBucket: 'elecko26-585b0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5nifY1s4HyYcTf3Kw63pDdFlN0mJ-FPA',
    appId: '1:813263083099:web:2b21915005a6e9c61e517e',
    messagingSenderId: '813263083099',
    projectId: 'elecko26-585b0',
    authDomain: 'elecko26-585b0.firebaseapp.com',
    storageBucket: 'elecko26-585b0.firebasestorage.app',
    measurementId: 'G-DN5Z23W3YE',
  );
}
