// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY', // Placeholder
    appId: '1:790419883700:web:4c97af722a4c7803c039e1',
    messagingSenderId: '790419883700',
    projectId: 'elecko26-536e0',
    authDomain: 'elecko26-536e0.firebaseapp.com',
    storageBucket: 'elecko26-536e0.appspot.com',
    measurementId: 'G-XXXXXXXXXX', // Placeholder
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY', // Placeholder
    appId: '1:790419883700:android:a74d49f37c68ea6fc039e1',
    messagingSenderId: '790419883700',
    projectId: 'elecko26-536e0',
    storageBucket: 'elecko26-536e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // Placeholder
    appId: '1:790419883700:ios:de3c8e5a2d00dd32c039e1',
    messagingSenderId: '790419883700',
    projectId: 'elecko26-536e0',
    storageBucket: 'elecko26-536e0.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID', // Placeholder
    iosBundleId: 'com.example.elecko26New', // Placeholder - need to verify this
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY', // Placeholder
    appId: '1:790419883700:ios:9cad0944b8e6542ec039e1',
    messagingSenderId: '790419883700',
    projectId: 'elecko26-536e0',
    storageBucket: 'elecko26-536e0.appspot.com',
    iosClientId: 'YOUR_MACOS_CLIENT_ID', // Placeholder
    iosBundleId: 'com.example.elecko26New', // Placeholder - need to verify this
  );
}
